builders:
  soti_schema:
    import: "package:soti_schema_plus/builder.dart"
    builder_factories: ["sotiSchemaBuilder"]
    # SharedPartBuilder emits `.g.part` fragments merged by the combining builder
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      soti_schema_plus|soti_schema:
        enabled: true
        generate_for:
          - test/**

