builders:
  spectraBuilder:
    import: "package:spectra/builder.dart"
    builder_factories: ["spectraBuilder"]
    build_extensions: {".dart": [".spectra.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
